# Generated by Django 5.0.6 on 2024-07-08 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('block_number', models.BigIntegerField(unique=True)),
                ('block_timestamp', models.BigIntegerField()),
                ('base_fee', models.BigIntegerField(default=0, null=True)),
                ('gas_used', models.BigIntegerField(default=0, null=True)),
                ('gas_limit', models.BigIntegerField(default=0, null=True)),
                ('reserve0', models.FloatField(default=0, null=True)),
                ('reserve1', models.FloatField(default=0, null=True)),
                ('amount0Diff', models.FloatField(default=0, null=True)),
                ('amount1Diff', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('sender', models.CharField(max_length=42, null=True)),
                ('to', models.CharField(max_length=42, null=True)),
                ('value', models.FloatField(default=0, null=True)),
                ('gas_limit', models.FloatField(default=0, null=True)),
                ('max_priority_fee_per_gas', models.FloatField(default=0, null=True)),
                ('max_fee_per_gas', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.IntegerField(default=0, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.block')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='SwapTokenForNative',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_in', models.FloatField(default=0, null=True)),
                ('amount_out_min_native', models.FloatField(default=0, null=True)),
                ('to', models.CharField(max_length=42, null=True)),
                ('deadline', models.BigIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.IntegerField(default=0, null=True)),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.transaction')),
            ],
            options={
                'db_table': 'swap_token_for_native',
            },
        ),
        migrations.CreateModel(
            name='Swap_Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=42, null=True)),
                ('to', models.CharField(max_length=42, null=True)),
                ('amount0_in', models.FloatField(default=0, null=True)),
                ('amount1_in', models.FloatField(default=0, null=True)),
                ('amount0_out', models.FloatField(default=0, null=True)),
                ('amount1_out', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.IntegerField(default=0, null=True)),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.transaction')),
            ],
            options={
                'db_table': 'swap_event',
            },
        ),
    ]
