# Generated by Django 5.0.6 on 2024-07-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='amount0Diff',
            new_name='amount0_diff',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='amount1Diff',
            new_name='amount1_diff',
        ),
    ]
