# Generated by Django 5.0.6 on 2024-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_rename_swap_event_swapevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_timestamp',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
