# Generated by Django 5.0.6 on 2024-07-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_alter_block_block_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swapevent',
            old_name='tx',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='swaptokenfornative',
            old_name='tx',
            new_name='transaction',
        ),
    ]
