# Generated by Django 5.0.6 on 2024-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_rename_tx_swapevent_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
