# Generated by Django 5.0.6 on 2024-07-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaptokenfornative',
            name='lead_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='console.block'),
        ),
    ]
